language: php

install:
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  
script: 
  - casperjs test Test.js
